# Generated by Django 2.1.4 on 2018-12-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
