# Generated by Django 2.1.4 on 2018-12-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
    ]
