# Generated by Django 2.1.4 on 2018-12-20 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_main', models.ImageField(upload_to='items/photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='items/photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='items/photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='items/photos/%Y/%m/%d/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('brand', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('new-label', 'New with label'), ('new', 'New'), ('perfect', 'Perfect'), ('very good', 'Very good'), ('good', 'Good')], max_length=50)),
                ('category', models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids')], max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('pink', 'Pink'), ('gray', 'Gray'), ('brown', 'Brown'), ('orange', 'Orange'), ('purple', 'Purple')], max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('swap', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
