# Generated by Django 2.1.4 on 2018-12-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='User',
            new_name='user',
        ),
    ]
