# Generated by Django 2.1.4 on 2018-12-20 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20181220_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
