# Generated by Django 2.1.4 on 2018-12-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20181220_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='photo_3',
        ),
    ]
